import { HttpStatus } from '@nestjs/common';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export type ProbremDetailOptions = {
  type?: string;
  status?: HttpStatus;
  detail?: string;
  instance?: string;
};

export class ProbremDetail {
  @ApiPropertyOptional({
    description: 'A URI reference that identifies the problem type.',
    example: 'https://example.com/probs/out-of-credit',
  })
  public readonly type?: string;

  @ApiProperty({
    description: 'A short, human-readable summary of the problem type.',
    example: 'You do not have enough credit.',
  })
  public readonly title: string;

  @ApiPropertyOptional({
    description:
      'The HTTP status code generated by the origin server for this occurrence of the problem.',
    example: HttpStatus.BAD_REQUEST,
    enum: HttpStatus,
  })
  public readonly status?: HttpStatus;

  @ApiPropertyOptional({
    description:
      'A human-readable explanation specific to this occurrence of the problem.',
    example: 'Your current balance is 30, but that costs 50.',
  })
  public readonly detail?: string;

  @ApiPropertyOptional({
    description:
      'A URI reference that identifies the specific occurrence of the problem.',
    example: '/account/12345/msgs/abc',
  })
  public readonly instance?: string;

  public constructor(title: string, options?: ProbremDetailOptions) {
    this.title = title;
    this.type = options?.type;
    this.status = options?.status;
    this.detail = options?.detail;
    this.instance = options?.instance;
  }
}
