coverage:
  status:
    project:
      default: false

      backend:
        flags:
          - backend
        informational: true

      backend-feature-shared:
        flags:
          - backend-feature-shared
        informational: true

      backend-feature-user:
        flags:
          - backend-feature-user
        informational: true

      backend-feature-circle:
        flags:
          - backend-feature-circle
        informational: true

      frontend:
        flags:
          - frontend
        informational: true

    patch:
      default:
        informational: true

flags:
  backend:
    paths:
      - apps/backend
    carryforward: true

  frontend:
    paths:
      - apps/frontend
    carryforward: true

  backend-feature-shared:
    paths:
      - libs/backend/feature/shared
    carryforward: true

  backend-feature-user:
    paths:
      - libs/backend/feature/user
    carryforward: true

  backend-feature-circle:
    paths:
      - libs/backend/feature/circle
    carryforward: true

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: true
