version: '3'

services:
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_CONTROLLER_BROKER_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  profiles:
    container_name: profiles
    build:
      context: .
      dockerfile: ./apps/profiles/Dockerfile
    restart: always
    environment:
      - KAFKA_BROKER_URL=kafka:9092
    ports:
      - 3001:3000
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  circles:
    container_name: circles
    build:
      context: .
      dockerfile: ./apps/circles/Dockerfile
    restart: always
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - PROFILES_SERVICE_URL=http://profiles:3000
    ports:
      - 3002:3000
    depends_on:
      kafka:
        condition: service_healthy
      profiles:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    environment:
      - PROFILES_SERVICE_URL=http://profiles:3000
      - CIRCLES_SERVICE_URL=http://circles:3000
    ports:
      - 3000:3000
    depends_on:
      profiles:
        condition: service_healthy
      circles:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://web:3000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  e2e:
    container_name: e2e
    profiles: ['test']
    build:
      context: .
      dockerfile: ./e2e/Dockerfile.e2e
    depends_on:
      web:
        condition: service_healthy
    environment:
      - CI=true
      - PLAYWRIGHT_BASE_URL=http://web:3000
    volumes:
      - ./e2e/playwright-report:/app/e2e/playwright-report
      - ./e2e/test-results:/app/e2e/test-results
