export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of profiles */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * @description Unique identifier for the profile
               * @example 0
               */
              id: string;
              /**
               * @description Name of the profile
               * @example Alice
               */
              name: string;
            }[];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * @description Name of the profile
             * @example Alice
             */
            name: string;
          };
        };
      };
      responses: {
        /** @description Profile registered successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Get a profile by ID */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /**
               * @description Unique identifier for the profile
               * @example 0
               */
              id: string;
              /**
               * @description Name of the profile
               * @example Alice
               */
              name: string;
            };
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Profile deleted successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * @description Name of the profile
             * @example Alice
             */
            name: string;
          };
        };
      };
      responses: {
        /** @description Profile updated successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': {
              /**
               * @description A short, human-readable summary of the problem type.
               * @example You do not have enough credit.
               */
              title: string;
              /**
               * @description A human-readable explanation specific to this occurrence of the problem.
               * @example Your current balance is 30, but that costs 50.
               */
              detail?: string;
              /**
               * @description The HTTP status code generated by the origin server for this occurrence of the problem.
               * @example 400
               */
              status?: number;
              /**
               * @description A URI reference that identifies the problem type.
               * @example https://example.com/probs/out-of-credit
               */
              type?: string;
              /**
               * @description A URI reference that identifies the specific occurrence of the problem.
               * @example /account/12345/msgs/abc
               */
              instance?: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
