import { z } from '@hono/zod-openapi';

export const ProblemDetail = z
  .object({
    title: z.string().openapi({
      description: 'A short, human-readable summary of the problem type.',
      example: 'You do not have enough credit.',
    }),

    detail: z.string().optional().openapi({
      description:
        'A human-readable explanation specific to this occurrence of the problem.',
      example: 'Your current balance is 30, but that costs 50.',
    }),

    status: z.number().optional().openapi({
      description:
        'The HTTP status code generated by the origin server for this occurrence of the problem.',
      example: 400,
    }),

    type: z.string().optional().openapi({
      description: 'A URI reference that identifies the problem type.',
      example: 'https://example.com/probs/out-of-credit',
    }),

    instance: z.string().optional().openapi({
      description:
        'A URI reference that identifies the specific occurrence of the problem.',
      example: '/account/12345/msgs/abc',
    }),
  })

  .openapi({
    description: 'Problem detail schema for error responses',
  });
